### ISSUE TITLE
Display warnings and not fail if a directory isn't readable

### ISSUE THREAD

**Issue by SpartakusMd** [wp-cli/find-command#23]
As WP CLI should be run with a non-root user, there appears the case when the current user won't have `read` permissions to a some directory. Please implement a soft fail for this case.

`PHP Fatal error:  Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/var/www/...) : failed to open dir: Permission denied in wp-cli/packages/vendor/wp-cli/find-command/src/Find_Command.php:199`

**Comment by danielbachhuber** [comment]
I actually ran into this yesterday :) Thanks for the report!
