### ISSUE TITLE
<path> is diplayed as &lt;path&gt; on https://developer.wordpress.org/cli/commands/find/

### ISSUE THREAD

**Issue by pmbaldha** [wp-cli/find-command#47]
Hello,

In Documentation, <find> is diplayed as &lt;path&gt; on https://developer.wordpress.org/cli/commands/find/. Please refer screenshot; http://tinypic.com/r/rgxuuw/9

**Comment by sasagar** [comment]
@schlessera 
Hi, as I talk about this issue with @swissspidy , this can be happened on any documentation.  
So I'd like to fix this on the handbook command.  
If I got any mistake about it, tell me about it.

**Comment by spicecadet** [comment]
This should do the trick: https://github.com/wp-cli/find-command/pull/56. Looks like backticks were making the entity show instead of rendering.
