### ISSUE TITLE
Install failed due to wp-cli 2.12 rquired

### ISSUE THREAD

**Issue by Lonni93** [wp-cli/find-command#79]
## Bug Report

- [X] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [X] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Trying to install the package on Debian 11 (already installed several days ago on a Debian 12 with no errors) and it failed because wp-cli 2.12 it's not installed. On the server I have wp-cli 2.12 and via cli it's not updatable.

**Describe how other contributors can replicate this bug**

Simple install of wp-cli downloading https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar and then tring to install find-command via wp --allow-root package install wp-cli/find-command

```bash
/usr/local/bin/wp-cli --allow-root package install wp-cli/find-command
Installing package wp-cli/find-command (dev-main || dev-master || dev-trunk)
Updating /root/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Generating rules
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Root composer.json requires wp-cli/find-command dev-main || dev-master || dev-trunk -> satisfiable by wp-cli/find-command[dev-main].
    - wp-cli/find-command dev-main requires wp-cli/wp-cli ^2.12 -> found wp-cli/wp-cli[2.11.0] but it does not match the constraint. See https://getcomposer.org/dep-on-root for details and assistance.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
---
Error: Package installation failed (Composer return code 2).
Reverted composer.json.
```

**Describe what you would expect as the correct outcome**

I expect a smooth install.

**Let us know what environment you are running this on**

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

php -v
PHP 8.3.14 (cli) (built: Nov 25 2024 18:22:19) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.14, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.14, Copyright (c), by Zend Technologies

wp cli info
OS:     Linux 5.10.0-33-amd64 #1 SMP Debian 5.10.226-1 (2024-10-03) x86_64
Shell:  /bin/bash
PHP binary:     /usr/bin/php8.3
PHP version:    8.3.14
php.ini used:   /etc/php/wp-cli/php8.3.ini
MySQL binary:   /usr/bin/mysql
MySQL version:  mysql  Ver 15.1 Distrib 10.5.26-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /root
WP-CLI packages dir:    /root/.wp-cli/packages/
WP-CLI cache dir:       /root/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:
WP-CLI version: 2.11.0

```

**Provide a possible solution**

If you happen to have a suggestion on how to fix this bug, please tell us in here.

Just leave this section out if you don't know how to fix it.

**Provide additional context/Screenshots**

If applicable, add screenshots to help explain (you can just drag&drop images into the Github issue).

**Comment by swissspidy** [comment]
You'll need to install the latest stable version using `wp package install wp-cli/find-command:@stable`. The dev version (main branch) requires "2.12.0" in preparation for the next release.
